meta:hooks:pre-push: Format printout
Forgot some newlines.

diff --git a/meta/git/hooks/pre-push b/meta/git/hooks/pre-push
--- a/meta/git/hooks/pre-push
+++ b/meta/git/hooks/pre-push
@@ -42,8 +42,9 @@ while read local_ref local_oid remote_ref remote_oid; do
 
 	commits="$(git rev-list -E --oneline --grep "$pattern" "$range")"
 	if [ -n "$commits" ]; then
-		printf >&2 "$local_ref: Commits in progress:\n%s" "$commits"
-		printf >&2 "Aborting push"
+		printf >&2 "$local_ref: Commits in progress:\n"
+		printf >&2 "%s\n" "$commits"
+		printf >&2 "Aborting push\n"
 		exit 1
 	fi
 done
